# New
name: Hello versions
on: [push]
jobs:
    print-hello:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
            - run: python hello.py
